### ISSUE TITLE
[fields 1.4.2] Can't update asset with added fields

### ISSUE THREAD

**Issue by jsamaniegog** [pluginsGLPI/fields#124] opened 2016-12-21 10:48 UTC
Hello  again,
I can't update asset with added fields. If i disable the plugin i can save it.

**Comment by trasher** [comment] 2016-12-21 12:21
I can't reproduce; editing asset is working well on my side.

Do you have any output in the logs?

**Comment by jsamaniegog** [comment] 2016-12-21 12:34
I have nothing in the logs... 
GLPI doesn't save the changes if the plugin is enable. But it saves changes to the added fields.

If I downgrade the plugin to version 1.3.2 it works perfectly

**Comment by trasher** [comment] 2016-12-21 15:13
A regression has been added in 1.4.1 release; but have been fixed in 1.4.2. It will be difficult to fix if I cannot reproduce :(

**Comment by jsamaniegog** [comment] 2016-12-21 17:12
Ok I followed the next steps on my test server:

1. Uninstall plugin and clean
2. Install version 1.3.2
3. Add block "test". Associated item type: Phones
4. Add new field. Type: Text (single line)
5. Go to a phone and modify the name for example (it works). Go to the block "test" and modify the new field (it works).
6. Upgrade to version 1.4.2
7. Repeat the step 5, you cannot change the field "name" of the phone..

I hope you can reproduce it now.

**Comment by trasher** [comment] 2016-12-22 07:39
Thanks for the details; I think I've got it.

Issue happens only if there is nothing but at "add tab" block linked; I was testing with a field added in the main form (which work; even if there also is a tab).

**Comment by trasher** [comment] 2016-12-22 08:11
OK, here is a try to fix:
```diff
diff --git a/inc/container.class.php b/inc/container.class.php
index 913cd05..58558de 100644
--- a/inc/container.class.php
+++ b/inc/container.class.php
@@ -1061,7 +1061,7 @@ class PluginFieldsContainer extends CommonDBTM {
          $data = $item->plugin_fields_data;
          //update data
          $container = new self();
-         if ($container->updateFieldsValues($data, isset($_REQUEST['massiveaction']), $item->getType())) {
+         if (count($data) == 0 || $container->updateFieldsValues($data, isset($_REQUEST['massiveaction']), $item->getType())) {
             return true;
          }
       }
@@ -1118,7 +1118,7 @@ class PluginFieldsContainer extends CommonDBTM {
          return $item->plugin_fields_data = $data;
       }
 
-      return $item->input = [];
+      return $item->plugin_fields_data = [];
    }
 
    /**
```

This should solve the exact problem reported here; but it may have board effects on other cases... Since we do not yet run unit tests on the plugin; it's a very huge job to find and test all possible affected use cases.

**Comment by jsamaniegog** [comment] 2016-12-22 08:39
Hi @trasher 
I just tested with these changes and it works!

**Comment by trasher** [comment] 2016-12-22 10:02
Cool, thanks :)

**Closed** 2016-12-30 07:05 UTC
