### ISSUE TITLE
0 ticket bug

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/fields#288] opened 2018-10-29 14:27 UTC
Hi,

GLPI : 9.3.1
Plugin : 1.8.2

I have 2 colored fields in tickets : one blue for elements and one green for validations.

When i try to add a red colored ticket i loop on the add page.
Debug mode show me this when i select the type ticket :

> PHP Notice: Undefined index: type in D:\xampp\htdocs\glpi\inc\ticket.class.php at line 6874
> PHP Notice: Undefined index: type in D:\xampp\htdocs\glpi\inc\ticket.class.php at line 6877

This error appear also with blue and green colored tabs.

**Comment by stonebuzz** [comment] 2020-01-23 08:11
Hi @boscorelly 

This issue hasn't evolved in a long time.

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:11 UTC
Labels: need feedback
