### ISSUE TITLE
Error during saving data

### ISSUE THREAD

**Issue by chauchse** [pluginsGLPI/fields#36] opened 2016-05-19 18:29 UTC
Hello,

I am trying to use this plugin. I have created a new tab linked to ticket with one multi line field and then "regenerer les bloc".

So i try to use this new field. And the i save it and this error message appears : 

PHP Warning: Missing argument 3 for PluginFieldsContainer::updateFieldsValues(), called in /var/www/glpi/plugins/fields/front/container.form.php on line 31 and defined in /var/www/glpi/plugins/fields/inc/container.class.php at line 650
PHP Notice: Undefined variable: itemtype in /var/www/glpi/plugins/fields/inc/container.class.php at line 662

Fatal error: Class 'PluginFieldsTable' not found in /var/www/glpi/plugins/fields/inc/container.class.php on line 663

**Comment by exebit** [comment] 2016-06-07 16:03
+1 I added new field to Contact object. File with new class (in **inc/** directory ) has **class PluginFieldsContactmatrix**.  When i try to fill new contact field and press Save, the is an error:
PHP Fatal error:  Class 'PluginFieldsMatrix' not found in glpi/plugins/fields/inc/container.class.php on line 66

**Comment by exebit** [comment] 2016-06-07 16:18
Currently use old commit bd3848819c5ee4d767bc445fea40fc2e2d056e4a. It hasn't this bug

**Comment by trasher** [comment] 2016-07-08 09:45
Could you please test with latest master? It should solve both issues.

**Comment by trasher** [comment] 2016-08-29 09:30
Should be fixed in 0.90-1.3; feel free to reopen the ticket if the issue is still present.

**Closed by trasher** 2016-08-29 09:30 UTC
Labels: bug
