### ISSUE TITLE
[Suggestion] Change field position in ticket forms

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/fields#117] opened 2016-12-17 01:40 UTC
Hi, 

Displaying fields at the end of the form make it really annoying and unnatural when creating a ticket or displaying a ticket.
Those fields might be quite important when reviewing a ticket and accessible quickly to the eye.
Maybe make an option for that ? 

Here is something i'm quite happy with on my test server... 

![image](https://cloud.githubusercontent.com/assets/22624975/21283422/0b5f1c22-c3a6-11e6-8b16-c6281288ffdc.png)

**Comment by trasher** [comment] 2017-01-11 15:36
As of GLPI 9.1.2, it will be possible to add contents at the beginning or at the end of a form; we can possibily add an option to choose the place, but this will not be much more customizable.

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement, question

**Comment by SebH2O** [comment] 2022-01-21 17:48
Hi, 

We are using the GLPI version 9.5.6 and recently installed the fields plugin v1.12.8. 
I have look different topics and this one is exactly the feature that I'm looking for. 
Could you please tell me if from the latest post (January 2020) comething has been improved to add more customization and be able to move the position of each specifi field?
For exemple, I would like add a new field near the "Category" field, another one close to the "Priority", another one just below the "Time to resolve" field etc...

Another topic, maybe it's not related to that plugin, do you have any idea if we can rename a default field proposed by GLPI?

Thanks for your feedback. Every ideas/remarks is welcome :)

Kind Regards,
Sébastien
