### ISSUE TITLE
Use tags in the field type URL

### ISSUE THREAD

**Issue by aivorra** [pluginsGLPI/fields#220] opened 2017-12-15 21:09 UTC
Hi, when I create a new field type URL on the my block tab, It would be great if I could add "tags" like "External Links" do.

For example: [LOGIN] [ID] [NAME] [LOCATION] [LOCATIONID] [IP] [MAC] [NETWORK] 
[DOMAIN] [SERIAL] [OTHERSERIAL] [USER] [GROUP] [REALNAME] [FIRSTNAME] 

It will depend where it is the tab.

This option allow us to integrate to other systems.

Best regards.

**Comment by stonebuzz** [comment] 2020-01-23 08:40
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:40 UTC
