### ISSUE TITLE
Fields filled with data from another ticket

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/fields#238] opened 2018-04-03 12:03 UTC
Sometimes when you open a ticket the extra fields are filled with data from another ticket.

**Comment by stonebuzz** [comment] 2020-01-23 08:32
Hi @titidelaff 

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed** 2023-10-30 08:39 UTC
Labels: need feedback
