### ISSUE TITLE
Fields not visibles for users

### ISSUE THREAD

**Issue by cayetano** [pluginsGLPI/fields#213] opened 2017-11-06 16:02 UTC
i'm migrate form GLPI 9.0 to 9.2 and Fields 1.4 to 1.7
adicional fields are not show to users, only for original gulp user

 
![sc1](https://user-images.githubusercontent.com/851876/32450305-2c4cbf84-c314-11e7-8eb7-71a2c433dec2.png)
![sc2](https://user-images.githubusercontent.com/851876/32450310-2e8b2eca-c314-11e7-9c36-441953f37820.png)

thanx

Regards
Cayetano

**Comment by cayetano** [comment] 2017-11-07 08:02
More Data:
Only Super-Admin User can access fields.
All other users no see the fields.

Regards
Cayetano

**Comment by cayetano** [comment] 2017-11-08 08:32
More Info
I Found this recurrent error in php-errors-log

------
  *** PHP Notice(8): Undefined index: entities_id
  Backtrace :
  plugins/fields/inc/field.class.php:550
  inc/plugin.class.php:1271                          PluginFieldsField::showForTab()
  inc/ticket.class.php:4080                          Plugin::doHook()
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

**Comment by romain1206** [comment] 2017-11-30 14:19
idem for me

**Comment by romain1206** [comment] 2017-12-01 11:05
`PHP Warning: include_once(/var/www/glpi/plugins/fields/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/fields/setup.php at line 68
PHP Warning: include_once(): Failed opening '/var/www/glpi/plugins/fields/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/glpi/plugins/fields/setup.php at line 68`

**Comment by trasher** [comment] 2017-12-01 12:42
You've certainly downloaded one of "Source code" archives, or trying to use a git clone. Please use official archive.

**Comment by romain1206** [comment] 2017-12-01 13:46
j'ai tenter les 2 pour le message c'est réglé mais ca ne corrige pas le soucis de l'interface simplifié.

c'est bizzare ce bug, a chaque version il revient.

**Comment by Wikiki** [comment] 2017-12-07 09:57
Hi,

no error message on our side, but we don't see custom fields on self-service form.
Do you know how to fix this ?

**Comment by Nisttra** [comment] 2018-04-24 08:57
Hi, I had the same issue and couldn't find a way to fix it (there was a way for the fields to appair but you had to go in another ticket first and then go back to the ticket creation and even if you could send this ticket, each user had to do this at each new connection).
So in the end I tried to work with 1.45 version of the plugin and for a time it worked perfectly but now all my plugins are always deactivated and say I need to "clean" them ("nettoyer" in french) and when I do that It work for a time but some time later (It can be 30s or 5min) it will go back to the "clean" thing...
(don't know if it's related to the Fields plugin version being too old maybe?)

**Comment by stonebuzz** [comment] 2020-01-23 08:40
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:40 UTC

**Comment by tprohor** [comment] 2022-08-29 10:10
Hi, this problem for GLPI version 10.0.2 is actual. How can I fix it?
