### ISSUE TITLE
Fields empty

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/fields#237] opened 2018-04-03 12:01 UTC
Hi,

I added two mandatory fields in the tickets, it happens some times when we open the tickets that the fields are empty, after reloading the page the content appears.

**Comment by Twentycents84** [comment] 2018-11-06 11:03
Same for me ! GLPI 9.3 and Plugin .1.8.2
And in simply interface i have an error in field.class line 547
regards

**Comment by stonebuzz** [comment] 2020-01-23 08:33
Hi @titidelaff 

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:33 UTC
Labels: need feedback
