### ISSUE TITLE
[Ticket creation] choose fields with template

### ISSUE THREAD

**Issue by Nico06140** [pluginsGLPI/fields#223] opened 2018-01-29 09:54 UTC
Hello, i'm sorry i don't know to put this post i'm new with git.
So i explain my demand.
on my conmany, we installed GLPI 9.1.6, we could install 9.2 if needed.
when i create a new field in ticket before "save button" we can see the field during the ticket creation that is great but i want to know if there is any possibilities to choose the fields with ticket template ? 
i have 9.2 on a test machine but with fields 1.7 it seems not working too.
Thanks.

**Comment by stonebuzz** [comment] 2020-01-23 08:43
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:43 UTC
