### ISSUE TITLE
Support infocom tab (was Field not saved when it's on a specific tab)

### ISSUE THREAD

**Issue by johannsan** [pluginsGLPI/fields#148] opened 2017-01-24 15:24 UTC
Hello,

When I add a text field on  computer principal tab, there is no problem,

But when the filed is on infocom tab, the value is not saved.

Is-it a bug?

Field v.1.4.3

**Comment by trasher** [comment] 2017-01-24 15:26
Hi,

Many issues have been fixed in the last 2 releases, please try with 1.4.5

**Comment by johannsan** [comment] 2017-01-24 16:14
The bug is also present with 1.4.5

**Comment by trasher** [comment] 2017-01-24 16:25
Ohhh... OK, I guess I got it. You are doing an uprade from an older version, don't you?
You cannot add fields in infocom tab (I guess this always have been a bit buggy); but that was possible on some past versions.

**Comment by johannsan** [comment] 2017-01-24 16:32
Yes, own version is 1.4.3.
I'hve tried to upgrade in 1.4.5.
Then, I try to add the field on infocom tab.
Will the bug be corrected or will it ever be possible?

**Comment by trasher** [comment] 2017-01-24 18:00
The original issue: https://github.com/pluginsGLPI/fields/issues/26

I can't say right now if that will be supported. Until recently, it was possible to add a bloc on "any" item subtype; but some were not working, for some reasons; and most were not relevant in facts. 

That is why we've decided to restrict the initial add.

Of course, adding support for new subtypes will be possible, I'll try to take a look on the infocom one.

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement
