### ISSUE TITLE
Possibility to add multiple fields

### ISSUE THREAD

**Issue by dan723** [pluginsGLPI/fields#87] opened 2016-11-26 22:14 UTC
It would be great to have the possibility to add multiple fileds, selecting the "+" option

Thanks

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement
