### ISSUE TITLE
Change associated items

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/fields#93] opened 2016-11-29 15:37 UTC
Actually, you can select linked items types when creating a new block, but you can't change once it has been created.

**Comment by Djiock** [comment] 2016-12-05 11:35
Hello !
I second this, that would be very helpfull !
Thanks

**Comment by Djiock** [comment] 2017-11-02 16:22
Hi !
Sorry to write again but as I wrote about a year ago this would be very useful... Any chance to have it implemented within the next months ?

Thanks very much

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement
