### ISSUE TITLE
ReadOnly field when solving or closing ticket

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/fields#128] opened 2016-12-27 10:30 UTC
Hi, I created a field in a new tab in the ticket. Only when the ticket is resolved, the field that was created is inaccessible. I wonder if you have any settings for the field not to be read only when it resolves or closes the ticket.

Thank you,
Sidnei

![image](https://cloud.githubusercontent.com/assets/2439826/21497774/8b1779f8-cc0e-11e6-93aa-3012d4683c50.png)

![image](https://cloud.githubusercontent.com/assets/2439826/21497816/9026bfd0-cc0e-11e6-93b3-656b782e605d.png)

**Comment by trasher** [comment] 2017-01-12 07:37
There is actually no way to keep field editable when a ticket is solved, no.

We could add a setting but as far as I can see, it would be a quite important job.

**Comment by sidneim** [comment] 2017-01-12 11:01
Hi trasher, sorry I have not returned before on this subject, but found a solution to this forcing situation by always leaving the field editable. It is in production tests here in the company and it is working, even when it edits the field with the ticket closed recording in the Ticket History.

Has been tampered with in the function below:

in inc\field.class.php line 774
```
static function prepareHtmlFields($fields, $items_id, $itemtype, $canedit = true,
                                     $show_table = true, $massiveaction = false) {

.....
        if (in_array($items_obj->fields['status'], $items_obj->getClosedStatusArray())
               || in_array($items_obj->fields['status'], $items_obj->getSolvedStatusArray())
               || $first_found_p['right'] != CREATE) {
            $canedit = true;
         }
```
If anyone else is willing to test there is the code that should be changed.

Thank you,
Sidnei

**Comment by GuiGuiSoft** [comment] 2018-03-20 13:57
Hello,

Thank you @sidneim ! I will use the same trick.
I guess it is a little "ugly" for a developer :smile: but I have no other choice if I want to use some custom fields for "post-treatment" categorization and learning.

Regards.

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement
