### ISSUE TITLE
error message in php log

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#33] opened 2016-04-21 09:53 UTC
2016-04-21 11:13:39 [636@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: simcorpbaadminrightsfield
  Backtrace :
  plugins\fields\inc\field.class.php:737             
  plugins\fields\inc\field.class.php:424             PluginFieldsField::prepareHtmlFields()
  plugins\fields\inc\container.class.php:526         PluginFieldsField::showForTabContainer()
  inc\commonglpi.class.php:469                       PluginFieldsContainer::displayTabContentForItem()
  ajax\common.tabs.php:94                            CommonGLPI::displayStandardTab()

**Comment by trasher** [comment] 2016-08-29 09:30
Should be fixed in 0.90-1.3; feel free to reopen the ticket if the issue is still present.

**Closed by trasher** 2016-08-29 09:30 UTC
Labels: bug
