### ISSUE TITLE
[1.4.5] Date field not saved

### ISSUE THREAD

**Issue by pcabreralallave** [pluginsGLPI/fields#147] opened 2017-01-20 17:14 UTC
A date field is not being saved, tested in two different enviroments with same results

![image](https://cloud.githubusercontent.com/assets/19557972/22158321/b186236a-df09-11e6-979a-e71ce32d34cf.png)

**Comment by trasher** [comment] 2017-01-23 06:35
Cannot reproduce here. Please give more details (container type, wich item, which profile, ...).

**Comment by trasher** [comment] 2017-02-06 07:07
Ping?

**Comment by trasher** [comment] 2017-02-28 14:01
Closing as no feedback

**Closed by trasher** 2017-02-28 14:01 UTC
Labels: invalid
