### ISSUE TITLE
Allow tab on user preferences

### ISSUE THREAD

**Issue by wawax** [pluginsGLPI/fields#5] opened 2015-09-30 13:53 UTC
It would be great to allow adding a tab in user's preferences

**Comment by trasher** [comment] 2017-01-25 14:24
till not possible actually... Current hooks are not called on user tabs as of GLPI 9.1.2

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement
