### ISSUE TITLE
Sub entities not activated 

### ISSUE THREAD

**Issue by juveboss** [pluginsGLPI/fields#243] opened 2018-04-28 08:48 UTC
Hello, i used the plugin fields glpi 9.2.2? 

I have a problem on sub entities ... yet the option is activated :(

thanks...

**Comment by stonebuzz** [comment] 2020-01-23 08:28
Hi @juveboss 

you version is very old,  you need toupdate to latest version (glpi and fields).

I am closing this issue, feel free to  reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:28 UTC
Labels: need feedback
