### ISSUE TITLE
Class not found when updating

### ISSUE THREAD

**Issue by Djiock** [pluginsGLPI/fields#50] opened 2016-08-08 16:38 UTC
Hello,
I created a simple line of text in new tab in "users", but when I try to update it I have a blank page and this error in my php log :
[Mon Aug 08 18:25:00 2016] [error] [client **.**.***.***] PHP Fatal error:  Class 'PluginFieldsPersonnalinformation' not found in /var/www/******.com/glpi/plugins/fields/inc/container.class.php on line 663, referer: https://******.com/glpi/front/user.form.php?id=251
On GLPI 0.85.4 with php5.3 with fields version  0.90-1.3

Thanks !

**Comment by Djiock** [comment] 2016-08-23 14:56
ERRATUM : the issue is with Fields 0.90-1.2. Can't find 0.90-1.3 despite being the last version displayed on http://plugins.glpi-project.org/#/plugin/field

Quick update, we updated GLPÏ to 0.90.5 and thus PHP to 5.5, same problem. But it works with version 0.90-1.1. Sticking with it for now !

Thanks

**Comment by SumErgoCogito** [comment] 2016-08-25 17:11
I have this same issue, but so far only on some fields I created for contracts. It only affects two contracts.

**Comment by trasher** [comment] 2016-08-29 08:44
Hello,

This issue should be fixed in the current master branch; and will be fixed in 0.90-1.3 when it will be released.

Indeed, the plugins website references this release which does not yet exists; sorry for that.

**Comment by trasher** [comment] 2016-08-29 09:30
Should be fixed in 0.90-1.3; feel free to reopen the ticket if the issue is still present.

**Closed by trasher** 2016-08-29 09:30 UTC
Labels: bug

**Comment by SumErgoCogito** [comment] 2016-08-30 22:13
Verified that release 1.3 fixed my issue. Thanks!
