### ISSUE TITLE
glpi 9.2 with fileds 1.7 unable to customize after creating 

### ISSUE THREAD

**Issue by dsever** [pluginsGLPI/fields#207] opened 2017-10-05 07:36 UTC
Hi, 

I'm getting problem with fields like after creating custom block with fields block is created for given "Associated item type", but is unaccessible again in Setup/Aditionnal fields configuraiton section with error:
"Security die. trying to load a forbidden class name".

Thanks

**Comment by mfaroux** [comment] 2017-10-11 12:11
Bonjour,
Lorsque l'on ajoute un champ de type "liste" à un bloc il est impossible de rentrer des valeurs dans la liste
Erreur suivante:
**_Fatal error: Uncaught exception 'RuntimeException' with message 'Attempt to load unsecure or missing /usr/share/glpi/files/_plugins/fields/front/test2fielddropdown.php!' in /usr/share/glpi/plugins/fields/front/commondropdown.php:10 Stack trace: #0 {main} thrown in /usr/share/glpi/plugins/fields/front/commondropdown.php on line 10_**

**Comment by Miminoux** [comment] 2017-10-12 14:52
Is'nt it related to this issue : https://github.com/pluginsGLPI/fields/issues/157 ?
It looks like the same bug as me, I gave there a workarround if you want (it might not work in all cases)

**Comment by mfaroux** [comment] 2017-10-13 06:37
Hi,
I fixed temporaly my problem by edit the file "setup.php" and modify the line 51.
I changed the path.

**Comment by dsever** [comment] 2017-10-16 15:58
What exactly have you entered as front path?

**Comment by mfaroux** [comment] 2017-10-23 14:16
Hi,
line 51, changed by the complete path:
"define("PLUGINFIELDS_FRONT_PATH", "/var/lib/glpi/files/_plugins/fields/front");"

**Comment by Megachip** [comment] 2019-01-11 11:44
How to upgrade to 1.7.3?

```
MySQL tables installation	
Security die. trying to load a forbidden class name
```

**Comment by Megachip** [comment] 2019-03-18 15:20
```
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  _e() method is deprecated 
```

**Comment by stonebuzz** [comment] 2020-01-23 08:40
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:40 UTC
