### ISSUE TITLE
probleme import FusionInventory

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/fields#137] opened 2017-01-06 15:47 UTC
Hello,
When the plugin is enabled, importing of xml files fusioninventory crash.
There is no problem when the inventory is made by the agent.

I use GLPI 9.1.1 - Fields 1.4.3 - debian 8 - PHP 5.6

log mysql 
`  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_fields` WHERE plugin_fields_containers_id =
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
  Backtrace :
  inc/commondbtm.class.php:263
  plugins/fields/inc/container.class.php:904         CommonDBTM->find()
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  ...ry/inc/inventorycomputerinventory.class.php:520 CommonDBTM->add()
  ...inventory/inc/inventoryruleimport.class.php:801 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  ...ventory/front/inventorycomputerimportxml.php:97 PluginFusioninventoryCommunication->handleOCSCommunication()`

log PHP
`2017-01-06 15:37:29 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: plugin_fields_containers_id
  Backtrace :
  plugins/fields/inc/container.class.php:900
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  ...ry/inc/inventorycomputerinventory.class.php:520 CommonDBTM->add()
  ...inventory/inc/inventoryruleimport.class.php:801 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  ...ventory/front/inventorycomputerimportxml.php:97 PluginFusioninventoryCommunication->handleOCSCommunication()
2017-01-06 15:37:29 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: plugin_fields_containers_id
  Backtrace :
  plugins/fields/inc/container.class.php:904
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  ...ry/inc/inventorycomputerinventory.class.php:520 CommonDBTM->add()
  ...inventory/inc/inventoryruleimport.class.php:801 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  ...ventory/front/inventorycomputerimportxml.php:97 PluginFusioninventoryCommunication->handleOCSCommunication()
2017-01-06 15:37:29 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/fields/inc/container.class.php:756
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  ...ry/inc/inventorycomputerinventory.class.php:520 CommonDBTM->add()
  ...inventory/inc/inventoryruleimport.class.php:801 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1427                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1459                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:375 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:127 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  ...ventory/front/inventorycomputerimportxml.php:97 PluginFusioninventoryCommunication->handleOCSCommunication()
`

Thanks

**Comment by alex8276** [comment] 2017-01-10 10:05
Hello,
If I modify the column "type" (dom => all) in "glpi_plugin_fileds_fields", there is no error but the tabs Computer and OS are not insert.

**Comment by trasher** [comment] 2017-01-10 10:13
Please try the fix proposed:
https://github.com/pluginsGLPI/fields/issues/126#issuecomment-271300130

**Comment by alex8276** [comment] 2017-01-10 11:03
Hello,
Thanks for your help
I removed the line 1121, the errors have disappear and import is (almost) ok , but the tabs Computer and OS are empty. 
[URL=http://www.hostingpics.net/viewer.php?id=953706Capture.png][IMG]http://img11.hostingpics.net/pics/953706Capture.png[/IMG][/URL]

**Comment by trasher** [comment] 2017-01-10 11:06
Can you confirm the issue disapear when you disable fields plugin?

**Comment by alex8276** [comment] 2017-01-10 11:09
Yes, i confirm that.

**Comment by trasher** [comment] 2017-01-10 11:12
OK, thanks. Do you have any fields configured on the computer asset? If there are, some of them are marked as required?

**Comment by alex8276** [comment] 2017-01-10 11:16
yes i have one fields but not required

**Comment by trasher** [comment] 2017-01-10 11:17
OK, thanks; I'll try to reproduce

**Comment by alex8276** [comment] 2017-01-10 11:17
thanks

**Comment by alex8276** [comment] 2017-01-10 11:24
Same if the block is disabled.

**Comment by trasher** [comment] 2017-01-10 12:50
I cannot reproduce :-/ I've tested against 9.1.1; 9.1/bugfixes branch and master... And in each case I get OS informations.

What version of FI are you using? Fields you have added are on the main computer tab?

**Comment by alex8276** [comment] 2017-01-10 13:17
I using FI 9.1+1.0 and FI 9.1+1.1 on 2 differents servers (Windows and Linux)
Yes the fields is on computer tab

**Comment by alex8276** [comment] 2017-01-10 14:08
the problem is présent only with xml files

**Comment by trasher** [comment] 2017-01-10 14:17
Oooh! I did not read the initial description well. Will try again; thanks :)

**Comment by alex8276** [comment] 2017-01-10 14:35
No problem ;)

**Comment by trasher** [comment] 2017-01-10 15:00
Think I got it finally! Could you please try with the following:
```diff
diff --git a/inc/container.class.php b/inc/container.class.php
index 09baa73..0f165ba 100644
--- a/inc/container.class.php
+++ b/inc/container.class.php
@@ -1064,8 +1064,8 @@ class PluginFieldsContainer extends CommonDBTM {
          if (count($data) == 0 || $container->updateFieldsValues($data, isset($_REQUEST['massiveaction']), $item->getType())) {
             return true;
          }
+         return $item->input = array();
       }
-      return $item->input = array();
    }
```

**Comment by alex8276** [comment] 2017-01-10 15:21
Thanks a lot, it seems ok !!

**Comment by trasher** [comment] 2017-01-10 15:33
Great! Tahnks for your tests; I have a few things to check, this will be part of the next release.

**Comment by alex8276** [comment] 2017-01-11 08:11
you're welcome. Thanks for your job!

**Closed** 2017-01-11 14:14 UTC
Labels: bug

**Comment by alex8276** [comment] 2017-11-08 19:44
Hello,
I have an similar error, when i Want to generate an object from plugin Order management, I have an error 500.

I have make the modification above but it don't work.
GLPI 9.1.6 - Fields 1.4.3

Log PHP :
2017-11-08 20:33:59 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: plugin_fields_containers_id
  Backtrace :
  plugins/fields/inc/container.class.php:900         
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  plugins/order/inc/link.class.php:912               CommonDBTM->add()
  plugins/order/inc/reception.class.php:725          PluginOrderLink->generateNewItem()
  plugins/order/inc/reception.class.php:613          PluginOrderReception::generateAsset()
  plugins/order/front/reception.form.php:79          PluginOrderReception->updateReceptionStatus()
2017-11-08 20:33:59 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: plugin_fields_containers_id
  Backtrace :
  plugins/fields/inc/container.class.php:904         
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  plugins/order/inc/link.class.php:912               CommonDBTM->add()
  plugins/order/inc/reception.class.php:725          PluginOrderLink->generateNewItem()
  plugins/order/inc/reception.class.php:613          PluginOrderReception::generateAsset()
  plugins/order/front/reception.form.php:79          PluginOrderReception->updateReceptionStatus()
2017-11-08 20:33:59 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: plugin_fields_containers_id
  Backtrace :
  plugins/fields/inc/container.class.php:751         
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  plugins/order/inc/link.class.php:912               CommonDBTM->add()
  plugins/order/inc/reception.class.php:725          PluginOrderLink->generateNewItem()
  plugins/order/inc/reception.class.php:613          PluginOrderReception::generateAsset()
  plugins/order/front/reception.form.php:79          PluginOrderReception->updateReceptionStatus()
2017-11-08 20:33:59 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/fields/inc/container.class.php:756         
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  plugins/order/inc/link.class.php:912               CommonDBTM->add()
  plugins/order/inc/reception.class.php:725          PluginOrderLink->generateNewItem()
  plugins/order/inc/reception.class.php:613          PluginOrderReception::generateAsset()
  plugins/order/front/reception.form.php:79          PluginOrderReception->updateReceptionStatus()

and log mysql:
2017-11-08 20:33:59 [2@srv-glpi]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_fields` WHERE plugin_fields_containers_id = 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
  Backtrace :
  inc/commondbtm.class.php:263                       
  plugins/fields/inc/container.class.php:904         CommonDBTM->find()
  plugins/fields/inc/container.class.php:746         PluginFieldsContainer::validateValues()
  plugins/fields/inc/container.class.php:1043        PluginFieldsContainer->updateFieldsValues()
  :                                                  PluginFieldsContainer::postItemAdd()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  plugins/order/inc/link.class.php:912               CommonDBTM->add()
  plugins/order/inc/reception.class.php:725          PluginOrderLink->generateNewItem()
  plugins/order/inc/reception.class.php:613          PluginOrderReception::generateAsset()
  plugins/order/front/reception.form.php:79          PluginOrderReception->updateReceptionStatus()

Regards

**Comment by alex8276** [comment] 2017-11-08 20:35
Sorry in test i had a version > 1.4.3
