### ISSUE TITLE
Data not save

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/fields#214] opened 2017-11-08 09:20 UTC
Hi
With 1.4.3 (Glpi >= 9.1.4 )  I can add a bloc in the management tab, but the data are not save.

Last version don't work (Impossible to add in a specific tab)

regards

**Comment by alex8276** [comment] 2017-11-08 15:54
Other problem, The fields  add on the tan note, problem ... are enable but not visible

**Comment by alex8276** [comment] 2017-11-08 15:55
Other problem, The fields add on the tabs note, problem ... are enable but not visible

**Comment by cedric-anne** [comment] 2018-05-07 14:42
I just checked on GLPI 9.2.3 with Fields 1.7.0 and I did not reproduce this bug. Can you try to update and check if you still have this problem ?

**Comment by cedric-anne** [comment] 2018-06-05 07:45
Hi,

As I cannot reproduce this issue, I close it.

Regards

**Closed by cedric-anne** 2018-06-05 07:45 UTC
