### ISSUE TITLE
Sql error when deleting a field

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/fields#218] opened 2017-12-06 18:03 UTC
I'm running GLPI 9.1.6 and plugin Fields 1.6.2
In Fields configuration, when I delete (permanently) a field from a block, I get an Sql error as follows.
Nevertheless, the field is correctly deleted, disappears from the tables.
It seems like the error occurs when the plugin tries to delete the field a 2nd time !

  SQL: ALTER TABLE  `glpi_plugin_fields_contractbloctests`
         DROP COLUMN `test2field`
  Error: Can't DROP 'test2field'; check that column/key exists
  Backtrace :
  ...lugins\fields\inc\contractbloctest.class.php:51 
  plugins\fields\inc\field.class.php:151             PluginFieldsContractbloctest::removeField()
  inc\commondbtm.class.php:1364                      PluginFieldsField->pre_deleteItem()
  plugins\fields\front\field.form.php:22             CommonDBTM->delete()

**Comment by cedric-anne** [comment] 2018-05-07 13:39
I do not reproduce this bug on GLPI 9.3-dev and Fields 1.7.0. Can you try to update and check if you still having this issue ?

**Comment by cedric-anne** [comment] 2018-06-05 07:48
Hi,

As I cannot reproduce this issue, I close it.

Regards

**Closed by cedric-anne** 2018-06-05 07:48 UTC
Labels: bug, need feedback
