### ISSUE TITLE
Can't see additional fields in user tabs

### ISSUE THREAD

**Issue by Miminoux** [pluginsGLPI/fields#157] opened 2017-02-09 13:38 UTC
Hi

First of all, thx a lot for your plugin.

I just migrated from GLPI 9.1.1 to 9.1.2 and field plugin from 1.3.1 to 1.5.0 and I can't see the additional fields I had on a user tab.
I can fill them on user creation but no chance to see values on my users (nor the old nor the new values).

Bye

**Comment by Miminoux** [comment] 2017-02-10 14:20
Hi,
I'd like to add that I can't update any additional field.
After this I decided to rollback to 1.3.1 and noticed that my tests were not complete, before I migrated from 0.90-1.1 to 1.3.1 the plugin worked but not since 1.3.1. In 1.3.1 I can see database values but I can't update or add them.
I'm now rolling back to 0.90-1.1 to see if I can do something.
Bye

**Comment by trasher** [comment] 2017-02-10 14:43
I guess you should try with 1.4.5 version of the plugin on glpi 9.1.2; sme changes on the 1.5 may have break you user stuff.

>I can fill them on user creation but no chance to see values on my users 

Could you check if values are stored in the database? On the display side, you have the field label but not the value?

Also, please check glpi logs to see if there is no warnign, notice or error spotted.

**Comment by Miminoux** [comment] 2017-02-13 11:29
I've tried version 1.4.5 and I have the same result with glpi 9.1.1 and glpi 9.1.2 : fields values already in database are visible but when I try to edit them, it does nothing (and no error is spotted nor in UI nor in glpi logs).

To be very precise, for example, I made a field named "Service" : 
![service_field](https://cloud.githubusercontent.com/assets/13215730/22881254/f73a9906-f1e5-11e6-932f-8675ea4233cb.PNG)
For this user, I have been able to set the value with an older version of fields plugin. Now I can't edit it. I've tried to add "8888" at the end of the existing value : "Contrôle de gestion 8888".
No error, no red bloc, nothing when click "Save" and when the user page reloads, the modification does not appear. In database, the value remains the same, I tried to look for it with : 
SELECT items_id,itemtype,servicefield
FROM `glpi_plugin_fields_userinfoscomplmentaires`
WHERE `servicefield` LIKE '%8888%';
Which answered nothing (0 lines matching where clause).

(PhpMyAdmin helped me out so I'm sure about syntax : 
SELECT items_id,itemtype,servicefield
FROM `glpi_plugin_fields_userinfoscomplmentaires`
WHERE `items_id` =599;
+----------+----------+----------------------+
| items_id | itemtype | servicefield         |
+----------+----------+----------------------+
|      599 | User     | Contrôle de gestion  |
+----------+----------+----------------------+

I can't rollback to glpi 9.0 (and a working fields plugin in version 0.90-1.1) and I found a workarround for my production matters.
Maybe I can manually add some tracer if you tell me where is mysql "update" in the code, do you think it can help ?

Bye

**Comment by Miminoux** [comment] 2017-02-13 12:55
How crazy !

I tried to remove my old fields and create a new one, it now works with glpi 9.1.2 and fields 1.4.5.

I think I will use this trick to have the plugin work again (business matters), but I can help if you want me to test more ideas (I have a "bugged" GLPI instance on a pre-prod server which I can manipulate as much as I want).

Thx anyway and once more, thx for the plugin !

**Comment by Miminoux** [comment] 2017-02-13 17:01
OMG I got it ! It took my day but I feel better now...

It is an entity problem. If I create the additional field in the Root entity, then it works. If I create it in a sub entity, it doen't. I am going to make sure about this with some tests but here is the most reliable way to make the bug happen : 
- create an sub entity (let's call it entA)
- create an fields container in entA
- create a number field named "Age" as a dom tab for users
- go to a user and change his "Age", it will never work.
- delete and then create the same container but in the root entity instead, it works fine (but all other ents will have that container).

By the way, I was trying to reproduce the exact same fields container to eventually see some differences in the database. And I ran into a strange thing : in the newly created container, its name in DB (in glpi_plugin_fields_containers) seems to be limited compared with the old version, for example, adding a container named "Infos complémentaires" has name "infoscomplmentaire" in 1.4.5 and has kept name "infoscomplmentaires" (ending 's') from older version

Bye bye

**Comment by jarugut** [comment] 2017-02-14 15:53
Hello,
I would like to contribute in the forum. I've gotten to show the old extra fields after upgrade the GLPI and the plugin. Currently I'm in GLPI 9.1 and plugin 1.4.5.

Checking the database tables of the plugin I've seen that in the glpi_plugin_fields_profiles 1  table,  the old additional fields are configured in the column right, as r or w. But  the new extra  fields  created  by  the new plugin in the right column always appear the number 4.

I've changed the old r and w by 4, and currently I can see in the forms the extra fields.

sorry for my english, I hope this can help you.

**Comment by Miminoux** [comment] 2017-02-15 15:55
Hi,
I hadn't the problem, this table is already full of 4 and 1 depending rights are "Read" or "Write".

But a tiny bug about that table is that it was growing a lot in earlier versions. I had like 300 entries with many duplicates on same (profile_id , container_id). I truncated it and then recreated the 13 entries I need and it now updates an entry when I change it with UI instead of inserting a new value. Maybe the plugin needs an update script from some older version to 1.4.5 to purge old entries.

Bye

**Comment by Miminoux** [comment] 2017-10-12 14:50
I just informing community that the bug is showing on GLPI 9.2 + Fields 1.7.0

I must declare all blocks in the root entity and use profiles to hide the fields depending on entities (to hide fields in entity A and show them in entity B, profiles in entity A must have no rights on the block whereas profiles in entity B have read or write right).

**Comment by stonebuzz** [comment] 2020-01-23 08:42
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:42 UTC
Labels: bug
