### ISSUE TITLE
Blank page after saving in Entities

### ISSUE THREAD

**Issue by adrianeladeira** [pluginsGLPI/fields#41] opened 2016-07-05 13:14 UTC
I am using glpi version 0.90.3 with plugin Fields version 0.90-1.2. I am facing some issues when adding a tab in Entities. After saving a blank page is displayed. Have you see this before ?

**Comment by orthagh** [comment] 2016-07-05 14:54
Hello @adrianeladeira 

Could you check in your glpi/files/_logs folder the files named sql-errors.log and php-errors.log if you find relative line to your issue (check timestamp for match).

**Comment by gradatextil** [comment] 2016-07-07 10:59
Hello
I use glpi 0.90.3 with plugin Fields version 0.90-1.2. I've created some fileds and if I click on the save button a blank page is displayed. In php-errors.log I have found this errors:
  *** PHP Warning(2): Missing argument 3 for PluginFieldsContainer::updateFieldsValues(), called in /home/webseite/gt-hardware/plugins/fields/front/container.form.php on line 31 and defined
  Backtrace :
  plugins/fields/inc/container.class.php:650         
  plugins/fields/front/container.form.php:31         PluginFieldsContainer->updateFieldsValues()
2016-07-07 12:46:40 [2@gt-webserver]
  *** PHP Notice(8): Undefined variable: itemtype
  Backtrace :
  plugins/fields/inc/container.class.php:662         
  plugins/fields/front/container.form.php:31         PluginFieldsContainer->updateFieldsValues()
Can you please tell me what is wrong?
Thank you for your Help

**Comment by orthagh** [comment] 2016-07-07 12:29
Hello @gradatextil 

Could you test the current master which, i think, already fix this issue : 
https://github.com/pluginsGLPI/fields/archive/master.zip

**Comment by trasher** [comment] 2016-08-29 09:30
Should be fixed in 0.90-1.3; feel free to reopen the ticket if the issue is still present.

**Closed by trasher** 2016-08-29 09:30 UTC
Labels: bug
