### ISSUE TITLE
Global view: modify heading "Plugins - myCustomFieldName"

### ISSUE THREAD

**Issue by aurygp** [pluginsGLPI/fields#219] opened 2017-12-11 18:21 UTC
Hi!
First thanks for this plugin! Is really helpful. 
I have a doubt. Is it possible to change or eliminate the heading with de prefix "plugins - " when I use it in a Global View?

For example in Home > Assitance > Tickets, when I "Select default items to show"  in Global view and I choose "custom fields"created before, the tag of column say "Plugins - myCustomFieldName". I only want to see myCustomFieldName.

Thanks a lot.
AuryGp

**Comment by cedric-anne** [comment] 2018-05-07 15:06
For information, it is a global behavior in GLPI core: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/search.class.php#L1390).
But I agree with you, I think the "Plugins -" prefix is not needed.

**Comment by stonebuzz** [comment] 2020-01-23 08:40
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:40 UTC
