### ISSUE TITLE
New field is not in ticket

### ISSUE THREAD

**Issue by belu33fr** [pluginsGLPI/fields#291] opened 2018-11-29 09:00 UTC
Hi,
Creat a new field for ticket.
When you create a new ticket from menu or from the list of ticket, no problem, the field is here.
When you create a ticket from a computer or another object, the field is not here.
thanks

**Comment by stonebuzz** [comment] 2020-01-23 08:08
Hi @belu33fr 

This issue hasn't evolved in a long time.

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (tested on latest version).

Best regards

**Comment by belu33fr** [comment] 2020-01-29 07:43
Hi @stonebuzz 
I'm sorry but the issue still right.
It is only when you open a ticket from a computer (example), not when you open a new ticket alone not from anything.
Best regards

**Comment by stonebuzz** [comment] 2020-01-29 08:06
Hi @belu33fr 

can you test with develop branch ?

Best regards

**Comment by belu33fr** [comment] 2020-01-29 23:41
Hi,
Sorry I try the develop branch and the plugin show error and needs cleanup. Normal?
For now, I reverse with backup.
Best regards

**Comment by stonebuzz** [comment] 2020-01-30 06:58
If you have download from here 

![image](https://user-images.githubusercontent.com/7335054/73427049-341f8f80-4336-11ea-87ce-93e476b5492d.png)

you need to rename folder to "fields"  rather than "fields-develop"

Best regards

**Comment by stonebuzz** [comment] 2020-01-30 07:02
For information, 
i'm not reproduce your problem with develop branch.

Bes tregards

**Closed** 2023-10-30 08:40 UTC
Labels: need feedback
