### ISSUE TITLE
Custom fields in assets can no longer be deleted

### ISSUE THREAD

**Issue by FreeMacs** [pluginsGLPI/fields#863] opened 2024-11-25 12:41 UTC
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

1.21.15

### Bug description

Since the update to 10.0.17, I can no longer delete the created fields. The option is completely missing although I am logged in as a super admin.

Here is the status of GLPI 10.0.16
![image](https://github.com/user-attachments/assets/3f865cb7-da95-45a6-adb9-8f11d58f5200)

Here is the status of GLPI 10.0.17
![image](https://github.com/user-attachments/assets/ee488686-222e-4a30-9be0-c5d6977e448b)

**Comment by cconard96** [comment] 2024-11-25 13:06
Duplicate of #859

**Closed** 2024-11-25 13:06 UTC
