### ISSUE TITLE
Can't export created fields in ticket as CSV 

### ISSUE THREAD

**Issue by schif1** [pluginsGLPI/fields#210] opened 2017-10-23 15:07 UTC
Hi,

I used this script to create new field in Ticket section of GLPI.
The new block type is "Insert in the form (before the save button)"
![image](https://user-images.githubusercontent.com/20978071/31896662-a2ef09f4-b814-11e7-8082-c483721c761a.png)

The fields within this block are:
heading
number
![image](https://user-images.githubusercontent.com/20978071/31896645-9d9a5292-b814-11e7-8495-b537d19c54ea.png)

All fields and bloc are active.

Thanks

**Comment by stonebuzz** [comment] 2020-01-23 08:40
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:40 UTC
