### ISSUE TITLE
Add custom Field to Ticket Task?

### ISSUE THREAD

**Issue by dan723** [pluginsGLPI/fields#86] opened 2016-11-26 22:05 UTC
I would like to add a custom field to a ticket task, it would be very useful.

Thanks

**Comment by dan723** [comment] 2016-11-26 22:07
I would like to add a custom field to a ticket task, it would be very useful.

Thanks

**Comment by dan723** [comment] 2016-12-30 14:14
Hi,
Any idea if it will be possible in a future release?
Thanks a lot

**Comment by trasher** [comment] 2016-12-30 15:38
This is not planned yet; I do not really have enough time to work on this right now.

**Comment by dan723** [comment] 2017-01-02 14:05
Ok, thanks

**Comment by dan723** [comment] 2017-04-19 19:50
Hi, 
Is this feature planned? 
It would be the last thing to complete the implementation of GLPI.
Thanks

**Comment by stonebuzz** [comment] 2020-01-23 08:41
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:41 UTC
Labels: enhancement

**Comment by EC2311** [comment] 2022-04-26 09:39
Hi @stonebuzz 
It's very sorry not to have possibility to add fields on tickets tasks [version fields : 1.12.8]
