### ISSUE TITLE
Modify bloc

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/fields#165] opened 2017-03-01 08:44 UTC
Hello,
Is it possible to add an element type after block's creation ?
Regards

**Comment by stonebuzz** [comment] 2020-01-23 08:42
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 08:42 UTC
Labels: enhancement
